meta_product_name: "Share Attraction"
meta_title: "Share Attraction - Engineered word of mouth"
meta_description: "With ShareAttraction, promote your content with the help of your community!"
meta_image: "https://images.unsplash.com/photo-1590615370581-265ae19a053b" # should exist in `app/assets/images/`
